name: YS/H
author: YS/H STUDY BLOG
baseurl: https://saewookr.github.io
description: Study blog
github: http://saewookr.github.io/
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.
plugins: [jekyll-paginate] 

paginate: 6
paginate_path: /page:num/

highlighter: rouge
markdown: kramdown

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

per_page: 20
gems: [jekyll-paginate, jekyll-gist]
  

      